### ISSUE TITLE
Content Security Policy failure with generated protobuf

### ISSUE THREAD

**Issue by jaitthomas** [improbable-eng/ts-protoc-gen#128]
In the --js_out="import_style" do you support the other format like commonjs_strict?. Currently the generated protobuf fails against the below security policy for commonjs. 

script-src www.google-analytics.com ajax.googleapis.com.

Probable cause for the  failure is below line in the generated file as function constructor.

var global = Function('return this')();

commonjs_strict/ES6 which seems to be the right fit, but doesn't seem to generate the javascript files. Expectation to avoid the global would be something like [this](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/js/js_generator.cc#L1676).

Any solution/workaround for this?

**Comment by jonnyreeves** [comment]
Hi @jaitthomas, sorry to read you are having issues, hopefully we can get this working for you!

Please could you start by confirming if this is an issue specifically with ts-protoc-gen rather than with protoc itself? (ie: do the security violations originate from the proto JavaScript or the grpc-web service stub (`*_pb_service.js`))

**Comment by jaitthomas** [comment]
Its generated from _pb.js as below.

`// GENERATED CODE -- DO NOT EDIT!`
`var jspb = require('google-protobuf');`
`var goog = jspb;`
`var global = Function('return this')(); // => This Function constructor might be the issue`
`goog.exportSymbol('proto.name', null, global);`

**Comment by jaitthomas** [comment]
Any updates on this?

**Comment by jaitthomas** [comment]
This issue is not just with ts-protoc-gen, also with google-protobuf. The strict mode provided by google protobuf, doesn't pass against its own CSP.  One way to solve the issue is to provide 'unsafe-eval' within the policy, which defeats the purpose of CSP.  Modes such as 'strict-dynamic' with whitelisting of sha-256/384/512 wasn't working for me at least.

If you are using webpack, workaround is to use a RegEx loader to replace this text 

var global = Function('return this')(); 

with equivalent of 

var global = (function(){ return this }).call(null);

Not sure if this has any other issues, atleast working so far.

**Comment by jonnyreeves** [comment]
Hi @jaitthomas, I'm glad you were able to find a workaround.

As you've identified, the root cause of this issue lies within the google-protobuf library, did you raise an issue upstream? 

If/when this gets fixed upstream I will be happy to accept any changes to ts-protoc-gen that are also required.

Until then I'll close this issue as wont-fix as I don't believe any action can be taken at present.

**Comment by BichengWang** [comment]
the struct_pb.js from "google-protobuf" 3.10.0 line 13 has the same problem, Content Security Policy failure.

**Comment by BichengWang** [comment]
```

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

```

**Comment by piotrkowalczuk** [comment]
fyi: Version `3.12.3` generates:
```
var jspb = require('google-protobuf');
var goog = jspb;
var proto = {};
```
