### ISSUE TITLE
Add a bazel flag for enabling/disabling conversion from CommonJS to AMD step.

### ISSUE THREAD

**Issue by pbsf** [improbable-eng/ts-protoc-gen#177]
I think it would be interesting to have a flag for enabling/disabling the conversion from the generated CommonJS code to AMD. On my project I'm currently using a copy of the `defs.bzl` file, removing the call to _convert_js_files_to_amd_modules for this plugin to work for a React Native scenario.

Thoughts?

**Comment by mattem** [comment]
I'm after something similar, as we need to take the generated protos into `rollup_bundle`. 
I don't think a flag is the correct approach here though, as it's normally down to the downstream rule to request the right output (AMD, es6 etc) rather than the user passing in a flag. 

I've been experimenting producing both es5 and es6 sources, instead of setting the es5 output to both:

```
es5_sources = es5_js_outputs + aspect_data.deps_js,
es6_sources = es5_js_outputs + aspect_data.deps_js,
```

**Comment by Dig-Doug** [comment]
I ran into the `rollup_bundle` problem as well today so took a stab at fixing the es6 output in #185.
