### ISSUE TITLE
Consider using ts-proto

### ISSUE THREAD

**Issue by stephenh** [improbable-eng/ts-protoc-gen#202]
This is just a shot-in-the-dark, and there'd be a lot of work to be done, but FWIW I just wanted to mention/you might be interested in [ts-proto](https://github.com/stephenh/ts-proto), which instead of generating `.d.ts` files on top of the google JS/etc. output, generates TS directly from its own protoc plugin.

Besides a simpler workflow, it also generates "idiomatic" TS output, i.e. data is just hashes, instead of classes with getters/setters.

Feel free to close / ignore because I don't have anything actionable per se; just wanted to mention the possibility if anyone was interested.

(Technically ts-proto is being used in production for server-side twirp RPC calls, so there would be some hopefully-minor work to also suppose grpc RPC calls, so, again disclaimer its not perfect/finished/etc., but fwiw/fyi/ymmv. :-))

**Comment by paambaati** [comment]
@stephenh Looks interesting; I'll be watching the project! I'm looking at a gRPC generator.

**Comment by jonny-improbable** [comment]
Thanks for sharing @stephenh. As you've probably gathered, the goal of this project is to produce complementary types to be used alongside the "official" google javascirpt protobuf generator. It's also (optionally) generates typed service stubs for use with @improbabl-eng/grpc-web although ideally that would be a seperate, standalone package (see #145).

I'm going to close this issue because, as you mentioned, as it's not actionable, however I'd be happy to accept a PR which links to it from the ts-protoc-gen README.
