### ISSUE TITLE
fromObject or Equivalent support

### ISSUE THREAD

**Issue by geekgonecrazy** [improbable-eng/ts-protoc-gen#9]
First this is awesome.  Loving being able to use typescript and grpc on the client.

The toObject function is perfect for being able to get a usable object.  But would be great to be able to convert back from an object.

So say i'm using one of these fancy frameworks with two way binding.  I do toObject... modify values, and then need to send it back.   Of course I can build the message manually.  But would be fantastic to be able to run a fromObject(object) and have a message ready to go.

**Comment by MarcusLongmuir** [comment]
Agreed. The discussion around the `fromObject` function appears to be happening [here on the protobuf project](https://github.com/google/protobuf/issues/1591).

Until it's available in the JavaScript output it would be difficult to add this function to the classes via this plugin.

**Comment by geekgonecrazy** [comment]
Is this a wontfix? Or why the close?

**Comment by MarcusLongmuir** [comment]
@geekgonecrazy: This functionality requires changes to `protoc` - in it's current form this plugin can only declare the contents of the JavaScript file that `protoc` generates. If you can propose a solution that doesn't require this change then we might be able to make progress, otherwise [this issue](https://github.com/google/protobuf/issues/1591) is the right place to pursue this.

**Comment by geekgonecrazy** [comment]
:+1: thanks for the upstream reference.  I'll track there
